<?php 
    echo $this->headMeta();
    echo $this->headLink();
?>

<div style="padding: 8px;" class ="login">
    <table >
        <tbody>
            <tr >
                <td class="formLabel" >Mã cây thành phẩm</td>
                <td class="formEdit"><?=$this->element->getElement('caythanhphamtim'); ?></td>
                <td style="padding-left: 40px;"><?=$this->element->getElement('them'); ?></td>
            </tr>
        </tbody>
    </table>
</div>