<?php
        echo $this->headMeta();
        echo $this->headLink();
        
        require_once '/../header.phtml';
        
        
        
        $hightlight ="" ;
        $choose = $this->param->getParams();
        
        if(array_key_exists('khachhang',$choose)) $hightlight = "khachhang";
        else if(array_key_exists('donhang',$choose)) $hightlight = "donhang";
        else if(array_key_exists('hopdong',$choose)) $hightlight = "hopdong";
        else if(array_key_exists('caymoc',$choose)) $hightlight = "caymoc";
        else if(array_key_exists('caymoc_detail',$choose)) $hightlight = "caymoc";
        else if(array_key_exists('taoctp',$choose)) $hightlight = "caythanhpham";
        else if(array_key_exists('lonhuom',$choose)) $hightlight = "lonhuom";
        else if(array_key_exists('khohang',$choose)) $hightlight = "khohang";
        else if(array_key_exists('caythanhpham',$choose)) $hightlight = "caythanhpham";
        else if(array_key_exists('ctp_detail',$choose)) $hightlight = "caythanhpham";
        else if(array_key_exists('khotp',$choose)) $hightlight = "khotp";
        else if(array_key_exists('donxuat',$choose)) $hightlight = "donxuat";
        else if(array_key_exists('hoadon',$choose)) $hightlight = "hoadon";
        else if(array_key_exists('loaivai',$choose)) $hightlight = "loaivai";
        else if(array_key_exists('loaisoi',$choose)) $hightlight = "loaisoi";
        else if(array_key_exists('mau',$choose)) $hightlight = "mau";
        else if(array_key_exists('nhacungcap',$choose)) $hightlight = "nhacungcap";
        else if(array_key_exists('khosoi',$choose)) $hightlight = "khosoi";
        else if(array_key_exists('khomoc',$choose)) $hightlight = "khomoc";
        else $hightlight = "donxuat";
        
        $router = Zend_Controller_Front::getInstance()->getRouter();
            
            
?>


<div id="mainql">
    <div style="float: left">
<!--         <p class="quanly_title">Quản lý dữ liệu</p> -->
        <div style="display:block" id = "mainmenu">
            <p <?php if($hightlight=="khachhang") echo 'class ="highlight"';?> ><a  href="<?php echo HOST_PROJECT."/index/export"?>">Khách Hàng</a></p>
            <p <?php if($hightlight=="donhang") echo 'class ="highlight"';?>><a  href="<?php echo HOST_PROJECT."/index/export"?>">Đơn Hàng</a></p>
            <p <?php if($hightlight=="hopdong") echo 'class ="highlight"';?>><a  href="<?php echo HOST_PROJECT."/index/export"?>">Hợp Đồng </a></p>
            <p <?php if($hightlight=="caymoc") echo 'class ="highlight"';?>><a  href="<?php echo HOST_PROJECT."/index/export"?>">Cây Mộc</a></p>
            <p <?php if($hightlight=="lonhuom") echo 'class ="highlight"';?>><a  href="<?php echo HOST_PROJECT."/index/export"?>">Lô Nhuộm</a></p>
            <p <?php if($hightlight=="caythanhpham") echo 'class ="highlight"';?>><a  href="<?php echo HOST_PROJECT."/index/export"?>">Cây Thành Phẩm</a></p>
            <p <?php if($hightlight=="donxuat") echo 'class ="highlight"';?>><a  href="<?php echo HOST_PROJECT."/index/export"?>">Đơn Xuất</a></p>
            <p <?php if($hightlight=="hoadon") echo 'class ="highlight"';?>><a  href="<?php echo HOST_PROJECT."/index/export"?>">Hóa Đơn</a></p>
            <p <?php if($hightlight=="loaivai") echo 'class ="highlight"';?>><a  href="<?php echo HOST_PROJECT."/index/export"?>">Loại Vải</a></p>
            <p <?php if($hightlight=="loaisoi") echo 'class ="highlight"';?>><a  href="<?php echo HOST_PROJECT."/index/export"?>">Loại Sợi</a></p>
            <p <?php if($hightlight=="mau") echo 'class ="highlight"';?>><a  href="<?php echo HOST_PROJECT."/index/export"?>">Màu</a></p>
            <p <?php if($hightlight=="khohang") echo 'class ="highlight"';?>><a  href="<?php echo HOST_PROJECT."/index/export"?>">Kho Hàng</a></p>
            <p <?php if($hightlight=="khosoi") echo 'class ="highlight"';?>><a  href="<?php echo HOST_PROJECT."/index/export"?>">Kho Sợi</a></p>
            <p <?php if($hightlight=="khomoc") echo 'class ="highlight"';?>><a  href="<?php echo HOST_PROJECT."/index/export"?>">Kho Mộc</a></p>
            <p <?php if($hightlight=="khotp") echo 'class ="highlight"';?>><a  href="<?php echo HOST_PROJECT."/index/export"?>">Kho TP</a></p>
            <p <?php if($hightlight=="nhacungcap") echo 'class ="highlight"';?>><a  href="<?php echo HOST_PROJECT."/index/export"?>">Nhà Cung Cấp</a></p>
            
        </div>
        <span style="clear: both"></span>
    </div>
 
</div>
<div id="bodycontent">
        <?php
    $khachhang = new Model_Khachhang();
    $donhang = new Model_Donhang();
    $loaivai = new Model_Loaivai();
    $donxuat= new Model_Donxuat();
    $donxuatall = $donxuat->getAll();
    
    if($donxuatall)
    {
        $data = new My_Data();
        $maincontent = array();
        $title = array("Mã Đơn Xuất","Khách Hàng","Ngày Xuất","Loại Vải","Số Mét","Thành Tiền", "Xuất File");
        
        foreach ($donxuatall as $donxuatrow)
        {
            $mydate = Zend_Locale_Format::getDate($donxuatrow['NgayXuat'],array("date_format"=>"yyyy.MM.dd"));
            $date_str =  $mydate['day']."/".$mydate['month']."/".$mydate['year'] ;
            $button= "<a class ='thembutton' href='".HOST_PROJECT."/index/export/madonxuat/".$donxuatrow['MaDonXuat']."'/>Xuất File</a>";
            
            $donhangrow = $donhang->getWhere($donxuatrow['MaDonHang']);
            $khachhangrow =$khachhang->getWhere($donhangrow['MaKhachHang']);
            $loaivairow = $loaivai->getWhere($donxuatrow['MaVai']);
            $tien = $data->convertCurrency(($donxuatrow['TongSoMet']*$donxuatrow['Gia']));
            $content = array(
                $donxuatrow['MaDonXuat'],$khachhangrow['TenKhachHang'],
                $date_str, $loaivairow['TenLoaiVai'],$donxuatrow['TongSoMet'],
                $tien,$button
            );
            $maincontent[] = $content;
        }
        $table = $data->createTable($title, $maincontent,"750px");
        echo $table;

    }
    else 
    {
        echo "<div class='message'>";
        echo "Chưa tồn tại Đơn Xuất";
        echo "</div>";
    }
    $expoetDx = $this->param->getParams();
//     $madx = $this->param->getParam("madonxuat");
    
    if (array_key_exists("madonxuat", $expoetDx)) {
        require_once 'data.php';
    }

    ?>