<?php
        echo $this->headMeta();
        echo $this->headLink();
        require_once '/../header.phtml';
        $hightlight ="" ;
        $choose = $this->param->getParams();
        
        if(array_key_exists('khachhang',$choose)) $hightlight = "khachhang";
        else if(array_key_exists('donhang',$choose)) $hightlight = "donhang";
        else if(array_key_exists('hopdong',$choose)) $hightlight = "hopdong";
        else if(array_key_exists('caymoc',$choose)) $hightlight = "caymoc";
        else if(array_key_exists('caymoc_detail',$choose)) $hightlight = "caymoc";
        else if(array_key_exists('taoctp',$choose)) $hightlight = "caythanhpham";
        else if(array_key_exists('lonhuom',$choose)) $hightlight = "lonhuom";
        else if(array_key_exists('khohang',$choose)) $hightlight = "khohang";
        else if(array_key_exists('caythanhpham',$choose)) $hightlight = "caythanhpham";
        else if(array_key_exists('ctp_detail',$choose)) $hightlight = "caythanhpham";
        else if(array_key_exists('khotp',$choose)) $hightlight = "khotp";
        else if(array_key_exists('donxuat',$choose)) $hightlight = "donxuat";
        else if(array_key_exists('hoadon',$choose)) $hightlight = "hoadon";
        else if(array_key_exists('loaivai',$choose)) $hightlight = "loaivai";
        else if(array_key_exists('loaisoi',$choose)) $hightlight = "loaisoi";
        else if(array_key_exists('mau',$choose)) $hightlight = "mau";
        else if(array_key_exists('nhacungcap',$choose)) $hightlight = "nhacungcap";
        else if(array_key_exists('khosoi',$choose)) $hightlight = "khosoi";
        else if(array_key_exists('khomoc',$choose)) $hightlight = "khomoc";
        else $hightlight = "khachhang";
        
        $router = Zend_Controller_Front::getInstance()->getRouter();
            
            
?>


<div id="mainql">
    <div style="float: left">
<!--         <p class="quanly_title">Quản lý dữ liệu</p> -->
        <div style="display:block" id = "mainmenu">
            <p <?php if($hightlight=="khachhang") echo 'class ="highlight"';?> ><a  href="<?php echo HOST_PROJECT."/index/main/khachhang"?>">Khách Hàng</a></p>
            <p <?php if($hightlight=="donhang") echo 'class ="highlight"';?>><a  href="<?php echo HOST_PROJECT."/index/main/donhang"?>">Đơn Hàng</a></p>
            <p <?php if($hightlight=="hopdong") echo 'class ="highlight"';?>><a  href="<?php echo HOST_PROJECT."/index/main/hopdong"?>">Hợp Đồng </a></p>
            <p <?php if($hightlight=="caymoc") echo 'class ="highlight"';?>><a  href="<?php echo HOST_PROJECT."/index/main/caymoc"?>">Cây Mộc</a></p>
            <p <?php if($hightlight=="lonhuom") echo 'class ="highlight"';?>><a  href="<?php echo HOST_PROJECT."/index/main/lonhuom"?>">Lô Nhuộm</a></p>
            <p <?php if($hightlight=="caythanhpham") echo 'class ="highlight"';?>><a  href="<?php echo HOST_PROJECT."/index/export"?>">Cây Thành Phẩm</a></p>
            <p <?php if($hightlight=="donxuat") echo 'class ="highlight"';?>><a  href="<?php echo HOST_PROJECT."/index/main/caythanhpham"?>">Đơn Xuất</a></p>
            <p <?php if($hightlight=="hoadon") echo 'class ="highlight"';?>><a  href="<?php echo HOST_PROJECT."/index/main/donxuat"?>">Hóa Đơn</a></p>
            <p <?php if($hightlight=="loaivai") echo 'class ="highlight"';?>><a  href="<?php echo HOST_PROJECT."/index/export"?>">Loại Vải</a></p>
            <p <?php if($hightlight=="loaisoi") echo 'class ="highlight"';?>><a  href="<?php echo HOST_PROJECT."/index/export"?>">Loại Sợi</a></p>
            <p <?php if($hightlight=="mau") echo 'class ="highlight"';?>><a  href="<?php echo HOST_PROJECT."/index/export"?>">Màu</a></p>
            <p <?php if($hightlight=="khohang") echo 'class ="highlight"';?>><a  href="<?php echo HOST_PROJECT."/index/export"?>">Kho Hàng</a></p>
            <p <?php if($hightlight=="khosoi") echo 'class ="highlight"';?>><a  href="<?php echo HOST_PROJECT."/index/export"?>">Kho Sợi</a></p>
            <p <?php if($hightlight=="khomoc") echo 'class ="highlight"';?>><a  href="<?php echo HOST_PROJECT."/index/export"?>">Kho Mộc</a></p>
            <p <?php if($hightlight=="khotp") echo 'class ="highlight"';?>><a  href="<?php echo HOST_PROJECT."/index/export"?>">Kho TP</a></p>
            <p <?php if($hightlight=="nhacungcap") echo 'class ="highlight"';?>><a  href="<?php echo HOST_PROJECT."/index/export"?>">Nhà Cung Cấp</a></p>
            
        </div>
        <span style="clear: both"></span>
    </div>
 
</div>
<div id="bodycontent">

<?php 
    
    if($this->param->getParam("khachhang_detail") == "true")
    {
        require_once 'khachhang_detail.php';
    }
    else if($this->param->getParam("hopdong_detail") == "true")
    {
        require_once 'hopdong_detail.php';
    }
    else if($this->param->getParam("caymoc_detail") == "true")
    {
        require_once 'caymoc_detail.php';
    }
    else if($this->param->getParam("lonhuom_detail") == "true")
    {
        require_once 'lonhuom_detail.php';
    }
    else if($this->param->getParam("ctp_detail") == "true")
    {
        require_once 'ctp_detail.php';
    }
    else if($this->param->getParam("kho_detail") == "true")
    {
        require_once 'kho_detail.php';
    }
    else if($this->param->getParam("donxuat_detail") == "true")
    {
        require_once 'donxuat_detail.php';
    }
    else if($this->param->getParam("congty") == "true")
    {
        require_once 'congty.php';
    }
    else 
    {
        require_once 'khachhang_all.php';
    }
      
?>
