<?php 
    echo $this->headMeta();
    echo $this->headLink();
    echo $this->headScript();
?>
<div id="header" >
    <div id="container">
        <ul >
            <li class="menu-item"><a href="<?php echo HOST_PROJECT."/index/xem/"?>">Quản Trị</a></li>
            <li  class="menu-item"><a href="<?php echo HOST_PROJECT."/index/main"?>" >Khách Hàng</a></li>
            <li class="menu-item"><a href="<?php echo HOST_PROJECT."/index/nhaplieu/muasoi/true"?>">Mua Sợi</a></li>
            <li class="menu-item"><a href="<?php echo HOST_PROJECT."/index/taichinh"?>">Tài Chính</a></li>
            <li class="menu-item"><a href="<?php echo HOST_PROJECT."/index/main/tim/true"?>">Tìm</a></li>
            <li class="menu-item"><a href="<?php echo HOST_PROJECT."/index/main/thongke/true"?>">Thống kê</a></li>
            <li class="menu-item"><a href="<?php echo HOST_PROJECT."/index/logout"?>">Logout</a></li>
        </ul>
    </div>
</div>
